import type { Agency, User, Client, Post, Metrics, SeoData, Report } from "@/types"

export const IS_DEMO = !process.env.NEXT_PUBLIC_SUPABASE_URL?.startsWith("http")

export const demoAgency: Agency = {
  id: "demo-agency-1",
  name: "Bright Social Agency",
  plan: "pro",
  created_at: "2024-01-01T00:00:00Z",
}

export const demoUser: User = {
  id: "demo-user-1",
  email: "demo@agencyos.com",
  full_name: "Alex Johnson",
  role: "owner",
  agency_id: "demo-agency-1",
  created_at: "2024-01-01T00:00:00Z",
}

export const demoClients: Client[] = [
  {
    id: "client-1",
    agency_id: "demo-agency-1",
    name: "Luminary Skincare",
    industry: "Beauty",
    website: "https://luminaryskincare.com",
    instagram: "@luminaryskin",
    facebook: "luminaryskincare",
    linkedin: "luminary-skincare",
    twitter: "@luminaryskin",
    brand_colors: ["#F4A5B2", "#FAD4C0", "#FFFFFF"],
    target_audience: "Women aged 25-40 interested in clean, sustainable beauty products",
    brand_voice: "Warm, empowering, and educational. Uses inclusive language with a focus on self-care rituals.",
    status: "active",
    health_score: 87,
    created_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "client-2",
    agency_id: "demo-agency-1",
    name: "TechVault Solutions",
    industry: "Technology",
    website: "https://techvault.io",
    instagram: "@techvault",
    linkedin: "techvault-solutions",
    twitter: "@techvaultio",
    brand_colors: ["#1E3A5F", "#00D4FF", "#FFFFFF"],
    target_audience: "CTOs and engineering managers at mid-size SaaS companies",
    brand_voice: "Professional, data-driven, and forward-thinking. Thought leadership tone.",
    status: "active",
    health_score: 72,
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "client-3",
    agency_id: "demo-agency-1",
    name: "Urban Bites Café",
    industry: "Food & Beverage",
    website: "https://urbanbites.co",
    instagram: "@urbanbites",
    facebook: "urbanbitescafe",
    twitter: "@urbanbitescafe",
    brand_colors: ["#2C1810", "#E8A045", "#F5F0EB"],
    target_audience: "Urban millennials aged 22-35 who love artisan coffee and healthy food",
    brand_voice: "Fun, casual, and community-focused. Heavy use of food emojis and local culture references.",
    status: "active",
    health_score: 91,
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "client-4",
    agency_id: "demo-agency-1",
    name: "Apex Fitness Co.",
    industry: "Health & Wellness",
    website: "https://apexfitness.com",
    instagram: "@apexfitness",
    facebook: "apexfitnessco",
    twitter: "@apexfitness",
    brand_colors: ["#FF4500", "#1A1A1A", "#FFFFFF"],
    target_audience: "Fitness enthusiasts aged 20-45 looking for premium gym equipment and training programs",
    brand_voice: "Motivational, energetic, and results-driven. Uses powerful action verbs and success stories.",
    status: "active",
    health_score: 65,
    created_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "client-5",
    agency_id: "demo-agency-1",
    name: "Verdant Realty",
    industry: "Real Estate",
    website: "https://verdantrealty.com",
    instagram: "@verdantrealty",
    linkedin: "verdant-realty",
    facebook: "verdantrealty",
    brand_colors: ["#2D6A4F", "#B7E4C7", "#FFFFFF"],
    target_audience: "First-time homebuyers and property investors in the Pacific Northwest",
    brand_voice: "Trustworthy, informative, and approachable. Uses clear language to demystify real estate.",
    status: "paused",
    health_score: 38,
    created_at: "2024-02-01T00:00:00Z",
  },
]

export const demoPosts: Post[] = [
  {
    id: "post-1",
    client_id: "client-1",
    platform: "instagram",
    caption: "✨ Your skin deserves the best. Introducing our new Radiance Serum — 98% natural ingredients, zero compromise. Tap the link in bio to shop. #CleanBeauty #SkincarRoutine #LuminarySkin",
    image_url: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800",
    status: "published",
    likes: 847,
    comments: 63,
    reach: 12400,
    scheduled_at: "2024-12-01T10:00:00Z",
    published_at: "2024-12-01T10:00:00Z",
    created_at: "2024-11-28T09:00:00Z",
  },
  {
    id: "post-2",
    client_id: "client-1",
    platform: "instagram",
    caption: "Morning ritual done right 🌿 Our Hydrating Mist is the first step to glowing skin. What's YOUR morning skincare routine? Tell us below! 👇",
    status: "scheduled",
    likes: 0,
    comments: 0,
    reach: 0,
    scheduled_at: "2025-01-20T09:00:00Z",
    created_at: "2025-01-10T14:00:00Z",
  },
  {
    id: "post-3",
    client_id: "client-2",
    platform: "linkedin",
    caption: "We surveyed 500 engineering teams and found that 73% lose more than 10 hours/week to manual deployment processes. Our new CI/CD integration cuts that to under 2 hours. Full report linked below.",
    status: "published",
    likes: 234,
    comments: 41,
    reach: 8900,
    published_at: "2024-12-05T14:00:00Z",
    created_at: "2024-12-03T10:00:00Z",
  },
  {
    id: "post-4",
    client_id: "client-3",
    platform: "instagram",
    caption: "Monday blues? Not on our watch ☕ Come in before 9am and get 20% off your order. Show this post at the counter. See you soon! 🤍 #UrbanBites #MondayMotivation #CoffeeLover",
    status: "pending_approval",
    likes: 0,
    comments: 0,
    reach: 0,
    scheduled_at: "2025-01-20T07:30:00Z",
    created_at: "2025-01-14T11:00:00Z",
  },
  {
    id: "post-5",
    client_id: "client-4",
    platform: "instagram",
    caption: "💪 No excuses. Our new Apex Pro Home Gym fits in any space and delivers gym-quality results. 30-day money back guarantee. Link in bio.",
    status: "draft",
    likes: 0,
    comments: 0,
    reach: 0,
    created_at: "2025-01-13T16:00:00Z",
  },
  {
    id: "post-6",
    client_id: "client-1",
    platform: "facebook",
    caption: "We're giving away a full Luminary Skincare bundle (worth $200)! To enter: 1) Like this post 2) Tag a friend who deserves to glow ✨ Winner announced Friday!",
    status: "published",
    likes: 1203,
    comments: 892,
    reach: 28500,
    published_at: "2024-11-15T12:00:00Z",
    created_at: "2024-11-13T10:00:00Z",
  },
  {
    id: "post-7",
    client_id: "client-3",
    platform: "facebook",
    caption: "NEW MENU ALERT 🍳 Our weekend brunch menu just dropped and it's everything. Avocado toast, shakshuka, and our famous cloud pancakes are back! Book your table now.",
    status: "published",
    likes: 445,
    comments: 78,
    reach: 9200,
    published_at: "2024-12-10T10:00:00Z",
    created_at: "2024-12-09T14:00:00Z",
  },
  {
    id: "post-8",
    client_id: "client-2",
    platform: "twitter",
    caption: "Just shipped: real-time collaboration in TechVault v3.2. Your whole team can now review deployments simultaneously. No more waiting for async reviews. 🚀",
    status: "published",
    likes: 156,
    comments: 22,
    reach: 4300,
    published_at: "2024-12-12T15:00:00Z",
    created_at: "2024-12-12T14:30:00Z",
  },
]

export const demoMetrics: Metrics[] = [
  // Luminary Skincare - Instagram
  { id: "m1", client_id: "client-1", platform: "instagram", followers: 42800, engagement_rate: 5.2, reach: 98000, impressions: 142000, recorded_at: "2024-10-01T00:00:00Z" },
  { id: "m2", client_id: "client-1", platform: "instagram", followers: 45100, engagement_rate: 5.6, reach: 106000, impressions: 158000, recorded_at: "2024-11-01T00:00:00Z" },
  { id: "m3", client_id: "client-1", platform: "instagram", followers: 48400, engagement_rate: 6.1, reach: 118000, impressions: 172000, recorded_at: "2024-12-01T00:00:00Z" },
  { id: "m4", client_id: "client-1", platform: "instagram", followers: 51200, engagement_rate: 5.8, reach: 124000, impressions: 183000, recorded_at: "2025-01-01T00:00:00Z" },
  // Luminary Skincare - Facebook
  { id: "m5", client_id: "client-1", platform: "facebook", followers: 18200, engagement_rate: 3.1, reach: 42000, impressions: 61000, recorded_at: "2024-10-01T00:00:00Z" },
  { id: "m6", client_id: "client-1", platform: "facebook", followers: 19100, engagement_rate: 3.4, reach: 46000, impressions: 67000, recorded_at: "2025-01-01T00:00:00Z" },
  // TechVault
  { id: "m7", client_id: "client-2", platform: "linkedin", followers: 8900, engagement_rate: 4.3, reach: 21000, impressions: 38000, recorded_at: "2024-10-01T00:00:00Z" },
  { id: "m8", client_id: "client-2", platform: "linkedin", followers: 10200, engagement_rate: 4.8, reach: 26000, impressions: 44000, recorded_at: "2025-01-01T00:00:00Z" },
  { id: "m9", client_id: "client-2", platform: "twitter", followers: 5400, engagement_rate: 2.9, reach: 12000, impressions: 19000, recorded_at: "2025-01-01T00:00:00Z" },
  // Urban Bites
  { id: "m10", client_id: "client-3", platform: "instagram", followers: 22300, engagement_rate: 7.2, reach: 54000, impressions: 78000, recorded_at: "2024-10-01T00:00:00Z" },
  { id: "m11", client_id: "client-3", platform: "instagram", followers: 24800, engagement_rate: 7.8, reach: 61000, impressions: 88000, recorded_at: "2025-01-01T00:00:00Z" },
  // Apex Fitness
  { id: "m12", client_id: "client-4", platform: "instagram", followers: 31000, engagement_rate: 3.8, reach: 67000, impressions: 95000, recorded_at: "2025-01-01T00:00:00Z" },
]

export const demoSeoData: SeoData = {
  id: "seo-1",
  client_id: "client-1",
  score: 74,
  keywords: [
    { keyword: "clean skincare", volume: 12400, ranking: 8, difficulty: 45 },
    { keyword: "natural face serum", volume: 8900, ranking: 14, difficulty: 52 },
    { keyword: "sustainable beauty", volume: 22100, ranking: 23, difficulty: 61 },
    { keyword: "hydrating mist", volume: 5600, ranking: 5, difficulty: 38 },
    { keyword: "cruelty free moisturizer", volume: 9800, ranking: 11, difficulty: 49 },
  ],
  competitors: [
    { name: "GlowLab", website: "glowlab.com", score: 82 },
    { name: "PureSkin Co.", website: "pureskinfo.com", score: 79 },
    { name: "Botanica Beauty", website: "botanicabeauty.com", score: 71 },
  ],
  recommendations: [
    "Add long-tail keywords targeting 'best clean serum for sensitive skin' to product pages",
    "Create a blog series on ingredient transparency to capture informational search traffic",
    "Optimize page load speed — current score 64/100, aim for 85+",
    "Add structured data markup for product pages to improve rich snippet eligibility",
    "Build 12+ backlinks from beauty publications in Q1 to close gap with GlowLab",
  ],
  recorded_at: "2025-01-10T00:00:00Z",
}

export const demoReport: Report = {
  id: "report-1",
  client_id: "client-1",
  month: "December 2024",
  content: {
    summary: "December was an outstanding month for Luminary Skincare across all social platforms. The holiday gift campaign drove significant engagement growth, with Instagram followers increasing by 6.4% month-over-month. The 'Glow Gift Guide' content series was our highest-performing campaign, generating 28,500 organic reach on Facebook alone.",
    highlights: [
      "Instagram followers grew from 45,100 to 51,200 (+13.5% MoM)",
      "Facebook giveaway reached 28,500 people — our best organic post ever",
      "Average engagement rate of 5.8% vs industry avg of 3.2%",
      "Holiday collection launch posts generated 847 saves on Instagram",
      "Website traffic from social up 34% compared to November",
    ],
    metrics_overview: "Total reach across all platforms reached 183,000 impressions in December, up 15.8% from November. Instagram remained the strongest channel with 5.8% engagement rate. Facebook showed strong growth driven by the giveaway campaign. LinkedIn and Twitter maintained steady performance.",
    top_posts: "The top performing post was the Facebook giveaway (28,500 reach, 1,203 likes, 892 comments). Second was the Instagram Radiance Serum launch post (12,400 reach, 847 likes). The 'Morning Ritual' Reel outperformed static posts by 2.4x in reach.",
    recommendations: "For January, we recommend: (1) Capitalize on 'new year, new skin' messaging with a 21-day skincare challenge campaign. (2) Increase Reels frequency to 3x/week based on December performance data. (3) Launch a UGC campaign to generate authentic social proof. (4) Test LinkedIn for the professional skincare audience segment.",
    next_month_goals: "January targets: 54,000 Instagram followers (+5.5%), 4.2M total impressions, launch skincare challenge campaign, publish 3 educational blog posts to support SEO strategy.",
  },
  created_at: "2025-01-05T00:00:00Z",
}

export const demoTeamMembers: User[] = [
  { id: "user-1", email: "alex@brightsoical.com", full_name: "Alex Johnson", role: "owner", agency_id: "demo-agency-1", created_at: "2024-01-01T00:00:00Z" },
  { id: "user-2", email: "sarah@brightsocial.com", full_name: "Sarah Chen", role: "admin", agency_id: "demo-agency-1", created_at: "2024-02-01T00:00:00Z" },
  { id: "user-3", email: "marcus@brightsocial.com", full_name: "Marcus Rivera", role: "editor", agency_id: "demo-agency-1", created_at: "2024-03-15T00:00:00Z" },
  { id: "user-4", email: "priya@brightsocial.com", full_name: "Priya Nair", role: "editor", agency_id: "demo-agency-1", created_at: "2024-04-01T00:00:00Z" },
  { id: "user-5", email: "tom@brightsocial.com", full_name: "Tom Wallace", role: "viewer", agency_id: "demo-agency-1", created_at: "2024-06-01T00:00:00Z" },
]
